#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpicxx simplestMPI.cpp  -o simplestMPIexe

## remove object files if there is any!:
# rm *.mod
# rm *.o

